---

- hosts: "{{ service }}"
  user: root
  any_errors_fatal: true
  gather_facts: yes
  vars:
    - service: ag-chain-cosmos
    - data: "{{ SETUP_HOME }}/{{ service }}/data"
  roles:
    - install-cosmos

