---

- hosts: ag-pserver
  user: root
  any_errors_fatal: true
  gather_facts: yes
  vars:
    - service: ag-pserver
    - data: "{{ SETUP_HOME }}/{{ service }}/data"
    - APPDIR: "{{lookup('pipe', 'pwd')}}/../.."
    - to_remove: "/home/{{ service }}/controller"
  roles:
    - copy
    - init
    - remove
    - init-controller
    - fetch-controller
