---

- name: Create service
  template:
    src: systemd.service.j2
    dest: "/etc/systemd/system/{{service}}.service"
    execline: "{{ execline }}"
  vars:
    execline: "/usr/src/ag-chain-cosmos/lib/ag-chain-cosmos start --proxy_app=kvstore"
  notify: reload services
