- name: "Ensure /home/{{ service }}/.{{ service }} exists"
  become_user: "{{ service }}"
  become: true
  file:
    path: "/home/{{ service }}/.{{ service }}"
    state: directory
    mode: 0755

- name: "Install {{ data | default(service + '/data') }}/cosmos-chain.json"
  become_user: "{{ service }}"
  become: true
  copy:
    src: "{{ data | default(service + '/data') }}/cosmos-chain.json"
    dest: "/home/{{ service }}/.{{ service }}/cosmos-chain.json"
    owner: "{{ service }}"
    group: "{{ service }}"
    mode: 0644

- name: "set-gci-ingress for controller"
  become_user: "{{ service }}"
  become: true
  shell:
    cmd: "ag-solo set-gci-ingress --chainID={{ CHAIN_NAME }} {{ GCI }} {{ RPC_ADDRS }}"
    chdir: "/home/{{ service }}/controller"
