---

- hosts: ag-pserver
  user: root
  #any_errors_fatal: true
  gather_facts: yes
  strategy: free
  vars:
    - service: ag-pserver
    - data: "{{ SETUP_HOME }}/{{ service }}/data"
    - APPDIR: "{{lookup('pipe', 'pwd')}}/../.."
    - HELPER_BINARY: "{{lookup('env', 'GOPATH') or '/usr/local'}}/bin/ag-cosmos-helper"
    - CHAIN_NAME: "{{ lookup('file', SETUP_HOME + '/ag-chain-cosmos/chain-name.txt') }}"
  roles:
    - copy
    - init
    - init-controller
    - fetch-controller
