- name: "Fetch {{ data | default(service + '/data') }}/*/genesis.json"
  fetch:
    dest: "{{ data | default(service + '/data') }}/{{ inventory_hostname }}/"
    flat: yes
    src: "/home/{{ service }}/.{{ service }}/config/genesis.json"

- name: "Get tendermint show-node-id output"
  become: yes
  become_user: "{{ service }}"
  shell: "{{ service }} tendermint show-node-id"
  register: chain_node_id

- name: "Create {{ data | default(service + '/data') }}/*/node-id"
  delegate_to: localhost
  copy:
    content: "{{ chain_node_id.stdout }}"
    dest: "{{ data | default(service + '/data') }}/{{ inventory_hostname }}/node-id"
