- name: "Fetch {{ genesis | default('genesis') }}/*/genesis.json"
  fetch:
    dest: "{{ genesis | default('genesis') }}/{{ inventory_hostname }}/"
    flat: yes
    src: "/home/{{ service }}/.{{ service }}/config/genesis.json"
