- name: "Initialize {{ service }}"
  become: yes
  become_user: "{{ service }}"
  shell: "{{ service }} init --chain-id={{ NETWORK_NAME }}"

- name: "Add coins to {{ service }}"
  become: yes
  become_user: "{{ service }}"
  shell: "{{ service }} add-genesis-account {{ BOOTSTRAP_ADDRESS }} {{ BOOTSTRAP_TOKENS }}"
