---

- name: reload daemon
  command: "systemctl daemon-reload"

- name: restart journalbeat
  service: name=journalbeat state=restarted

- name: restart rsyslog
  service: name=rsyslog state=restarted
