- name: "Ensure /home/{{ service }}/.ag-pserver/wwwroot/{{ CHAIN_NAME }} exists"
  become: yes
  become_user: "{{ service }}"
  file:
    path: "/home/{{ service }}/.ag-pserver/wwwroot/{{ CHAIN_NAME }}"
    state: directory

- name: "Create provisioning mnemonic"
  delegate_to: localhost
  shell:
    cmd: "ag-cosmos-helper keys mnemonic | tee provisioning-mnemonic.txt"
  register: mnemonic

- name: "Create {{ service }} ag-solo key"
  become: yes
  become_user: "{{ service }}"
  shell:
    cmd: "ag-cosmos-helper --home=.{{ service }}/ag-cosmos-helper-statedir --keyring-backend=test keys add ag-solo"
    stdin: "{{ mnemonic.stdout_lines }}"

- name: "Create ag-cosmos-helper-address"
  become: yes
  become_user: "{{ service }}"
  shell:
    cmd: "ag-cosmos-helper --home=.{{ service }}/ag-cosmos-helper-statedir \
      --keyring-backend=test keys show -a ag-solo > .{{ service }}/ag-cosmos-helper-address"
