name: Webhooks

on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:
  test-agoric-sdk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        owner_repo:
        - agoric-labs/dapp-token-economy

    steps:
    # Trigger the
    # on:
    #  repository_dispatch:
    #    types: [test-agoric-sdk]
    # actions.
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.TEST_REPO_TOKEN }}
        repository: ${{ matrix.owner_repo }}
        event-type: test-agoric-sdk
        client-payload: '{"ref": "${{ github.ref }}"}'

    - id: split
      uses: actions/github-script@0.9.0
      with:
        script: |
          const [owner, repo] = '${{ matrix.owner_repo }}'.split('/');
          core.setOutput('owner', owner);
          core.setOutput('repo', repo);

    # This step will retry until required check passes
    # and will fail the whole workflow if the check conclusion is not a success
    - name: Wait on build
      uses: fountainhead/action-wait-for-check@v1.0.0
      with:
        ref: main # can be commit SHA or tag too
        owner: ${{ steps.split.outputs.owner }}
        repo: ${{ steps.split.outputs.repo }}
        checkName: build # name of the existing check
        token: ${{ secrets.TEST_REPO_TOKEN }}
        intervalSeconds: 20 # seconds
